"""First migration

Revision ID: 566d06bce250
Revises: 
Create Date: 2022-06-10 15:37:27.953774

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "566d06bce250"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_urls_alias"), "urls", ["alias"], unique=True)
    op.create_index(op.f("ix_urls_target_url"), "urls", ["target_url"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urls_target_url"), table_name="urls")
    op.drop_index(op.f("ix_urls_alias"), table_name="urls")
    op.drop_table("urls")
    # ### end Alembic commands ###
